
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Image image2;
	private global::Gtk.Label label2;
	private global::Gtk.HSeparator hseparator1;
	private global::Gtk.Frame frame3;
	private global::Gtk.Alignment GtkAlignment2;
	private global::Gtk.Table table2;
	private global::Gtk.Label passlabel;
	private global::Gtk.Entry passwordEntry;
	private global::Gtk.Entry userEntry;
	private global::Gtk.Label userlabel;
	private global::Gtk.Label GtkLabel3;
	private global::Gtk.HSeparator hseparator3;
	private global::Gtk.Frame frame1;
	private global::Gtk.Alignment GtkAlignment1;
	private global::Gtk.Table table3;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView email_entry;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TextView body_text;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Entry attach_box;
	private global::Gtk.Button button1;
	private global::Gtk.Button button2;
	private global::Gtk.CheckButton htmlCheck;
	private global::Gtk.Label label4;
	private global::Gtk.Label label5;
	private global::Gtk.Label label6;
	private global::Gtk.Label label7;
	private global::Gtk.Entry subject_entry;
	private global::Gtk.Label GtkLabel4;
	private global::Gtk.Expander email_expand;
	private global::Gtk.VBox vbox9;
	private global::Gtk.Label label3;
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	private global::Gtk.TextView fix_email_entry;
	private global::Gtk.Label GtkLabel7;
	private global::Gtk.Frame frame2;
	private global::Gtk.VBox vbox8;
	private global::Gtk.Label label1;
	private global::Gtk.HBox hbox3;
	private global::Gtk.ProgressBar message_progress;
	private global::Gtk.Button sendbtn;
	private global::Gtk.Label GtkLabel6;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Postman");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource ("postman.mail.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(5));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.image2 = new global::Gtk.Image ();
		this.image2.Name = "image2";
		this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("postman.mail.png");
		this.hbox4.Add (this.image2);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.image2]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Postman</b>\n<span color='gray'>(c) 2011 Joseph Lewis &lt;joehms22@gmail.com&gt;\nGNU GPL V 2.0 | Icon from The Oxygen Team</span>");
		this.label2.UseMarkup = true;
		this.hbox4.Add (this.label2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label2]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox2.Add (this.hbox4);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.vbox2.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator1]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame ();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.table2 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.passlabel = new global::Gtk.Label ();
		this.passlabel.Name = "passlabel";
		this.passlabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Gmail Password:");
		this.table2.Add (this.passlabel);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.passlabel]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.passwordEntry = new global::Gtk.Entry ();
		this.passwordEntry.CanFocus = true;
		this.passwordEntry.Name = "passwordEntry";
		this.passwordEntry.Text = global::Mono.Unix.Catalog.GetString ("password");
		this.passwordEntry.IsEditable = true;
		this.passwordEntry.Visibility = false;
		this.passwordEntry.InvisibleChar = '•';
		this.table2.Add (this.passwordEntry);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.passwordEntry]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.userEntry = new global::Gtk.Entry ();
		this.userEntry.CanFocus = true;
		this.userEntry.Name = "userEntry";
		this.userEntry.Text = global::Mono.Unix.Catalog.GetString ("someone@gmail.com");
		this.userEntry.IsEditable = true;
		this.userEntry.InvisibleChar = '•';
		this.table2.Add (this.userEntry);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.userEntry]));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.userlabel = new global::Gtk.Label ();
		this.userlabel.Name = "userlabel";
		this.userlabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Gmail Username:");
		this.table2.Add (this.userlabel);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.userlabel]));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment2.Add (this.table2);
		this.frame3.Add (this.GtkAlignment2);
		this.GtkLabel3 = new global::Gtk.Label ();
		this.GtkLabel3.Name = "GtkLabel3";
		this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Account Information</b>");
		this.GtkLabel3.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel3;
		this.vbox2.Add (this.frame3);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame3]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hseparator3 = new global::Gtk.HSeparator ();
		this.hseparator3.Name = "hseparator3";
		this.vbox2.Add (this.hseparator3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator3]));
		w12.Position = 3;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 0.99F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.table3 = new global::Gtk.Table (((uint)(5)), ((uint)(2)), false);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(6));
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.email_entry = new global::Gtk.TextView ();
		this.email_entry.CanFocus = true;
		this.email_entry.Name = "email_entry";
		this.email_entry.WrapMode = ((global::Gtk.WrapMode)(2));
		this.email_entry.PixelsAboveLines = 5;
		this.GtkScrolledWindow.Add (this.email_entry);
		this.table3.Add (this.GtkScrolledWindow);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table3 [this.GtkScrolledWindow]));
		w14.LeftAttach = ((uint)(1));
		w14.RightAttach = ((uint)(2));
		// Container child table3.Gtk.Table+TableChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.body_text = new global::Gtk.TextView ();
		this.body_text.CanFocus = true;
		this.body_text.Name = "body_text";
		this.body_text.WrapMode = ((global::Gtk.WrapMode)(2));
		this.GtkScrolledWindow1.Add (this.body_text);
		this.table3.Add (this.GtkScrolledWindow1);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table3 [this.GtkScrolledWindow1]));
		w16.TopAttach = ((uint)(2));
		w16.BottomAttach = ((uint)(3));
		w16.LeftAttach = ((uint)(1));
		w16.RightAttach = ((uint)(2));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.attach_box = new global::Gtk.Entry ();
		this.attach_box.CanFocus = true;
		this.attach_box.Name = "attach_box";
		this.attach_box.IsEditable = false;
		this.attach_box.InvisibleChar = '•';
		this.hbox1.Add (this.attach_box);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.attach_box]));
		w17.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseStock = true;
		this.button1.UseUnderline = true;
		this.button1.Label = "gtk-add";
		this.hbox1.Add (this.button1);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button1]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseStock = true;
		this.button2.UseUnderline = true;
		this.button2.Label = "gtk-delete";
		this.hbox1.Add (this.button2);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button2]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		this.table3.Add (this.hbox1);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table3 [this.hbox1]));
		w20.TopAttach = ((uint)(4));
		w20.BottomAttach = ((uint)(5));
		w20.LeftAttach = ((uint)(1));
		w20.RightAttach = ((uint)(2));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.htmlCheck = new global::Gtk.CheckButton ();
		this.htmlCheck.CanFocus = true;
		this.htmlCheck.Name = "htmlCheck";
		this.htmlCheck.Label = global::Mono.Unix.Catalog.GetString ("Body Is HTML");
		this.htmlCheck.DrawIndicator = true;
		this.htmlCheck.UseUnderline = true;
		this.table3.Add (this.htmlCheck);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table3 [this.htmlCheck]));
		w21.TopAttach = ((uint)(3));
		w21.BottomAttach = ((uint)(4));
		w21.LeftAttach = ((uint)(1));
		w21.RightAttach = ((uint)(2));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Attachment:");
		this.table3.Add (this.label4);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table3 [this.label4]));
		w22.TopAttach = ((uint)(4));
		w22.BottomAttach = ((uint)(5));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("To:");
		this.table3.Add (this.label5);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table3 [this.label5]));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Subject:");
		this.table3.Add (this.label6);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table3 [this.label6]));
		w24.TopAttach = ((uint)(1));
		w24.BottomAttach = ((uint)(2));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Body:");
		this.table3.Add (this.label7);
		global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table3 [this.label7]));
		w25.TopAttach = ((uint)(2));
		w25.BottomAttach = ((uint)(3));
		w25.XOptions = ((global::Gtk.AttachOptions)(4));
		w25.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.subject_entry = new global::Gtk.Entry ();
		this.subject_entry.CanFocus = true;
		this.subject_entry.Name = "subject_entry";
		this.subject_entry.IsEditable = true;
		this.subject_entry.InvisibleChar = '•';
		this.table3.Add (this.subject_entry);
		global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table3 [this.subject_entry]));
		w26.TopAttach = ((uint)(1));
		w26.BottomAttach = ((uint)(2));
		w26.LeftAttach = ((uint)(1));
		w26.RightAttach = ((uint)(2));
		w26.XOptions = ((global::Gtk.AttachOptions)(4));
		w26.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment1.Add (this.table3);
		this.frame1.Add (this.GtkAlignment1);
		this.GtkLabel4 = new global::Gtk.Label ();
		this.GtkLabel4.Name = "GtkLabel4";
		this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Message</b>");
		this.GtkLabel4.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel4;
		this.vbox2.Add (this.frame1);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame1]));
		w29.Position = 4;
		// Container child vbox2.Gtk.Box+BoxChild
		this.email_expand = new global::Gtk.Expander (null);
		this.email_expand.HeightRequest = 0;
		this.email_expand.CanFocus = true;
		this.email_expand.Name = "email_expand";
		// Container child email_expand.Gtk.Container+ContainerChild
		this.vbox9 = new global::Gtk.VBox ();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("I was unable to recognize these email addresses please fix them and re-enter them in the \"To:\" field.");
		this.vbox9.Add (this.label3);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.label3]));
		w30.Position = 0;
		w30.Expand = false;
		w30.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.fix_email_entry = new global::Gtk.TextView ();
		this.fix_email_entry.CanFocus = true;
		this.fix_email_entry.Name = "fix_email_entry";
		this.GtkScrolledWindow2.Add (this.fix_email_entry);
		this.vbox9.Add (this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.GtkScrolledWindow2]));
		w32.Position = 1;
		this.email_expand.Add (this.vbox9);
		this.GtkLabel7 = new global::Gtk.Label ();
		this.GtkLabel7.Name = "GtkLabel7";
		this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Email Fix</b>");
		this.GtkLabel7.UseMarkup = true;
		this.GtkLabel7.UseUnderline = true;
		this.email_expand.LabelWidget = this.GtkLabel7;
		this.vbox2.Add (this.email_expand);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.email_expand]));
		w34.Position = 5;
		w34.Expand = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame2.Gtk.Container+ContainerChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<span color='red'>Do not quit the program before all messages have been sent.</span>\nUpon pressing send, the message above will be sent to each person in the to field individually.");
		this.label1.UseMarkup = true;
		this.label1.Justify = ((global::Gtk.Justification)(2));
		this.vbox8.Add (this.label1);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.label1]));
		w35.Position = 0;
		w35.Expand = false;
		w35.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.message_progress = new global::Gtk.ProgressBar ();
		this.message_progress.Name = "message_progress";
		this.hbox3.Add (this.message_progress);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.message_progress]));
		w36.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.sendbtn = new global::Gtk.Button ();
		this.sendbtn.CanFocus = true;
		this.sendbtn.Name = "sendbtn";
		this.sendbtn.UseUnderline = true;
		// Container child sendbtn.Gtk.Container+ContainerChild
		global::Gtk.Alignment w37 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w38 = new global::Gtk.HBox ();
		w38.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w39 = new global::Gtk.Image ();
		w39.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Menu);
		w38.Add (w39);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w41 = new global::Gtk.Label ();
		w41.LabelProp = global::Mono.Unix.Catalog.GetString ("Send");
		w41.UseUnderline = true;
		w38.Add (w41);
		w37.Add (w38);
		this.sendbtn.Add (w37);
		this.hbox3.Add (this.sendbtn);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.sendbtn]));
		w45.Position = 1;
		w45.Expand = false;
		w45.Fill = false;
		this.vbox8.Add (this.hbox3);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox3]));
		w46.Position = 1;
		w46.Expand = false;
		w46.Fill = false;
		this.frame2.Add (this.vbox8);
		this.GtkLabel6 = new global::Gtk.Label ();
		this.GtkLabel6.Name = "GtkLabel6";
		this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Send</b>");
		this.GtkLabel6.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel6;
		this.vbox2.Add (this.frame2);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame2]));
		w48.PackType = ((global::Gtk.PackType)(1));
		w48.Position = 6;
		w48.Expand = false;
		w48.Fill = false;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 724;
		this.DefaultHeight = 616;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button1.Pressed += new global::System.EventHandler (this.add_attachment);
		this.button2.Pressed += new global::System.EventHandler (this.del_attachment);
		this.body_text.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.leave_body);
		this.email_entry.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.leave_to);
		this.sendbtn.Released += new global::System.EventHandler (this.send_mail_event);
	}
}
