#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sat Feb 27 13:35:04 2010

import wx

# begin wxGlade: extracode
import wx.html as html
from Lib.Code import Parser
import sys
from Lib.Code import Frontend
import wxmpl
# end wxGlade

class CalcWidget(wx.Frame,Frontend.events):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CalcWidget.__init__
        kwds["style"] = wx.CAPTION|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.MAXIMIZE_BOX|wx.SYSTEM_MENU|wx.RESIZE_BORDER|wx.FULL_REPAINT_ON_RESIZE|wx.TAB_TRAVERSAL|wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        self.main_window = wx.SplitterWindow(self, -1, style=wx.SP_3DBORDER|wx.SP_BORDER|wx.SP_LIVE_UPDATE)
        self.help_browser_panel = wx.Panel(self.main_window, -1)
        self.main_panel = wx.Panel(self.main_window, -1)
        self.notebook_manager = wx.Notebook(self.main_panel, -1, style=0)
        self.graphs_panel = wx.Panel(self.notebook_manager, -1)
        self.functions_panel = wx.Panel(self.notebook_manager, -1)
        self.pad_panel = wx.Panel(self.notebook_manager, -1)
        
        # Menu Bar
        self.main_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        self.switch_to_pad_menu_item = wx.MenuItem(wxglade_tmp_menu, wx.NewId(), "&Switch To Pad\tCtrl+Shift+P", "Switch the view to the pad", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.switch_to_pad_menu_item)
        wxglade_tmp_menu.AppendSeparator()
        self.clear_pad_menu_item = wx.MenuItem(wxglade_tmp_menu, wx.NewId(), "&Clear\tCtrl+K", "Clear the pad.", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.clear_pad_menu_item)
        self.main_menubar.Append(wxglade_tmp_menu, "&Pad")
        self.functions_menu = wx.Menu()
        self.switch_to_function_menu_item = wx.MenuItem(self.functions_menu, wx.NewId(), "&Switch To Functions\tCtrl+Shift+F", "Switch the view to the function area.", wx.ITEM_NORMAL)
        self.functions_menu.AppendItem(self.switch_to_function_menu_item)
        self.functions_menu.AppendSeparator()
        self.functions_menu.Append(wx.NewId(), "&Clear All Functions", "", wx.ITEM_NORMAL)
        self.main_menubar.Append(self.functions_menu, "&Functions")
        self.graph_menu = wx.Menu()
        self.switch_to_graphs_menu_item = wx.MenuItem(self.graph_menu, wx.NewId(), "&Swith To Graphs\tCtrl+Shift+G", "Switch the view to graphs.", wx.ITEM_NORMAL)
        self.graph_menu.AppendItem(self.switch_to_graphs_menu_item)
        self.graph_menu.AppendSeparator()
        self.save_graph = wx.MenuItem(self.graph_menu, wx.NewId(), "Save As", "Save the current graph as an image.", wx.ITEM_NORMAL)
        self.graph_menu.AppendItem(self.save_graph)
        self.main_menubar.Append(self.graph_menu, "&Graphs")
        self.SetMenuBar(self.main_menubar)
        # Menu Bar end
        self.main_statusbar = self.CreateStatusBar(1, wx.ST_SIZEGRIP)
        self.output_text_ctrl = wx.TextCtrl(self.pad_panel, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY)
        self.input_text_ctrl = wx.TextCtrl(self.pad_panel, -1, "")
        self.button_3 = wx.Button(self.pad_panel, -1, "&Submit")
        self.functions_list_box = wx.ListBox(self.functions_panel, -1, choices=[])
        self.label_2 = wx.StaticText(self.functions_panel, -1, "Y=")
        self.function_text_ctrl = wx.TextCtrl(self.functions_panel, -1, "")
        self.label_3 = wx.StaticText(self.functions_panel, -1, "Color:")
        self.function_color_combo_box = wx.ComboBox(self.functions_panel, -1, choices=["Blue", "Cyan", "Green", "Black", "Magenta", "Yellow"], style=wx.CB_DROPDOWN|wx.CB_READONLY)
        self.label_4 = wx.StaticText(self.functions_panel, -1, "Style:")
        self.function_style_combo_box = wx.ComboBox(self.functions_panel, -1, choices=["Solid Line", "Dashed Line", "Dash - Dot Line", "Dotted Line"], style=wx.CB_DROPDOWN)
        self.label_5 = wx.StaticText(self.functions_panel, -1, "Name:")
        self.function_name_text_ctrl = wx.TextCtrl(self.functions_panel, -1, "")
        self.function_show_checkbox = wx.CheckBox(self.functions_panel, -1, "Show")
        self.functions_ok_button = wx.Button(self.functions_panel, wx.ID_OK, "")
        self.function_cancel_button = wx.Button(self.functions_panel, wx.ID_CANCEL, "")
        self.graph_2d_plot_panel = wxmpl.PlotPanel(self.graphs_panel, -1)
        self.label_8_copy_3 = wx.StaticText(self.graphs_panel, -1, "Presets:")
        self.combo_box_1 = wx.ComboBox(self.graphs_panel, -1, choices=["Trig", "Standard"], style=wx.CB_DROPDOWN)
        self.label_6 = wx.StaticText(self.graphs_panel, -1, "X Min:")
        self.text_ctrl_1 = wx.TextCtrl(self.graphs_panel, -1, "-10")
        self.label_7 = wx.StaticText(self.graphs_panel, -1, "X Max:")
        self.text_ctrl_1_copy_2 = wx.TextCtrl(self.graphs_panel, -1, "10")
        self.label_8 = wx.StaticText(self.graphs_panel, -1, "Y Min:")
        self.text_ctrl_1_copy = wx.TextCtrl(self.graphs_panel, -1, "-10")
        self.label_8_copy = wx.StaticText(self.graphs_panel, -1, "Y Max:")
        self.text_ctrl_1_copy_3 = wx.TextCtrl(self.graphs_panel, -1, "10")
        self.checkbox_1 = wx.CheckBox(self.graphs_panel, -1, "3D Graph")
        self.label_8_copy_2 = wx.StaticText(self.graphs_panel, -1, "Z Min:")
        self.text_ctrl_1_copy_1 = wx.TextCtrl(self.graphs_panel, -1, "-10")
        self.label_8_copy_1 = wx.StaticText(self.graphs_panel, -1, "Z Max:")
        self.text_ctrl_1_copy_4 = wx.TextCtrl(self.graphs_panel, -1, "10")
        self.table_panel = wx.Panel(self.notebook_manager, -1)
        self.bitmap_button_1 = wx.BitmapButton(self.help_browser_panel, -1, wx.Bitmap("./Lib/Icons/go-home.png", wx.BITMAP_TYPE_ANY))
        self.panel_2 = wx.Panel(self.help_browser_panel, -1)
        self.label_1 = wx.StaticText(self.help_browser_panel, -1, "Help Browser", style=wx.ALIGN_CENTRE)
        self.html_window = html.HtmlWindow(self.help_browser_panel, -1)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.switch_to_pad, self.switch_to_pad_menu_item)
        self.Bind(wx.EVT_MENU, self.clear_pad, self.clear_pad_menu_item)
        self.Bind(wx.EVT_MENU, self.switch_to_functions, self.switch_to_function_menu_item)
        self.Bind(wx.EVT_MENU, self.switch_to_graphs, self.switch_to_graphs_menu_item)
        self.Bind(wx.EVT_MENU, self.save_graph_as, self.save_graph)
        self.Bind(wx.EVT_BUTTON, self.Submit_Input, self.button_3)
        self.Bind(wx.EVT_LISTBOX, self.update_function_editor, self.functions_list_box)
        self.Bind(wx.EVT_BUTTON, self.submit_function, self.functions_ok_button)
        self.Bind(wx.EVT_BUTTON, self.update_function_editor, self.function_cancel_button)
        self.Bind(wx.EVT_NOTEBOOK_PAGE_CHANGED, self.notebook_page_changed, self.notebook_manager)
        self.Bind(wx.EVT_BUTTON, self.LoadPage, self.bitmap_button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: CalcWidget.__set_properties
        self.SetTitle("OpenCalc")
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("./Lib/Icons/main_icon.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetSize((640, 515))
        self.main_statusbar.SetStatusWidths([-1])
        # statusbar fields
        main_statusbar_fields = ["OpenCalc 10.0 Stable"]
        for i in range(len(main_statusbar_fields)):
            self.main_statusbar.SetStatusText(main_statusbar_fields[i], i)
        self.input_text_ctrl.SetFocus()
        self.function_color_combo_box.SetSelection(0)
        self.function_style_combo_box.SetSelection(0)
        self.function_name_text_ctrl.Enable(False)
        self.function_show_checkbox.SetValue(1)
        self.combo_box_1.SetSelection(1)
        self.text_ctrl_1_copy_1.Enable(False)
        self.text_ctrl_1_copy_4.Enable(False)
        self.bitmap_button_1.SetSize(self.bitmap_button_1.GetBestSize())
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: CalcWidget.__do_layout
        main_sizer = wx.BoxSizer(wx.VERTICAL)
        help_browser_sizer = wx.BoxSizer(wx.VERTICAL)
        help_browser_title_sizer = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_8_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(self.output_text_ctrl, 1, wx.ALL|wx.EXPAND, 5)
        sizer_3.Add(self.input_text_ctrl, 0, wx.ALL|wx.EXPAND, 5)
        sizer_3.Add(self.button_3, 0, wx.ALL|wx.ALIGN_RIGHT, 5)
        self.pad_panel.SetSizer(sizer_3)
        sizer_5.Add(self.functions_list_box, 2, wx.ALL|wx.EXPAND, 5)
        sizer_6.Add(self.label_2, 0, 0, 0)
        sizer_6.Add(self.function_text_ctrl, 0, wx.EXPAND, 0)
        sizer_6.Add(self.label_3, 0, 0, 0)
        sizer_6.Add(self.function_color_combo_box, 0, wx.EXPAND, 0)
        sizer_6.Add(self.label_4, 0, 0, 0)
        sizer_6.Add(self.function_style_combo_box, 0, wx.EXPAND, 0)
        sizer_6.Add(self.label_5, 0, 0, 0)
        sizer_6.Add(self.function_name_text_ctrl, 0, wx.EXPAND, 0)
        sizer_6.Add(self.function_show_checkbox, 0, 0, 0)
        sizer_7.Add(self.functions_ok_button, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_7.Add(self.function_cancel_button, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add(sizer_7, 0, wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_5.Add(sizer_6, 0, wx.ALL|wx.EXPAND, 5)
        self.functions_panel.SetSizer(sizer_5)
        sizer_1.Add(self.graph_2d_plot_panel, 1, wx.ALL|wx.EXPAND, 5)
        sizer_4.Add(self.label_8_copy_3, 0, 0, 0)
        sizer_4.Add(self.combo_box_1, 0, wx.EXPAND, 0)
        sizer_9.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_8.Add(self.label_6, 0, 0, 0)
        sizer_8.Add(self.text_ctrl_1, 0, 0, 0)
        sizer_8.Add(self.label_7, 0, 0, 0)
        sizer_8.Add(self.text_ctrl_1_copy_2, 0, 0, 0)
        sizer_9.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_8_copy.Add(self.label_8, 0, 0, 0)
        sizer_8_copy.Add(self.text_ctrl_1_copy, 0, 0, 0)
        sizer_8_copy.Add(self.label_8_copy, 0, 0, 0)
        sizer_8_copy.Add(self.text_ctrl_1_copy_3, 0, 0, 0)
        sizer_9.Add(sizer_8_copy, 1, wx.EXPAND, 0)
        sizer_9.Add(self.checkbox_1, 0, 0, 0)
        sizer_8_copy_1.Add(self.label_8_copy_2, 0, 0, 0)
        sizer_8_copy_1.Add(self.text_ctrl_1_copy_1, 0, 0, 0)
        sizer_8_copy_1.Add(self.label_8_copy_1, 0, 0, 0)
        sizer_8_copy_1.Add(self.text_ctrl_1_copy_4, 0, 0, 0)
        sizer_9.Add(sizer_8_copy_1, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_9, 0, wx.EXPAND, 0)
        self.graphs_panel.SetSizer(sizer_1)
        self.notebook_manager.AddPage(self.pad_panel, "Pad")
        self.notebook_manager.AddPage(self.functions_panel, "Functions")
        self.notebook_manager.AddPage(self.graphs_panel, "Graphs")
        self.notebook_manager.AddPage(self.table_panel, "Tables")
        sizer_2.Add(self.notebook_manager, 1, wx.EXPAND, 0)
        self.main_panel.SetSizer(sizer_2)
        help_browser_title_sizer.Add(self.bitmap_button_1, 0, 0, 0)
        help_browser_title_sizer.Add(self.panel_2, 1, wx.EXPAND, 0)
        help_browser_title_sizer.Add(self.label_1, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 8)
        help_browser_sizer.Add(help_browser_title_sizer, 0, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 1)
        help_browser_sizer.Add(self.html_window, 1, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        self.help_browser_panel.SetSizer(help_browser_sizer)
        self.main_window.SplitVertically(self.main_panel, self.help_browser_panel)
        main_sizer.Add(self.main_window, 1, wx.EXPAND, 0)
        self.SetSizer(main_sizer)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class CalcWidget


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    Main_Frame = CalcWidget(None, -1, "")
    app.SetTopWindow(Main_Frame)
    #Redirect stdout to the pad
    sys.stdout=Main_Frame
    #Make it setup my way
    Main_Frame.setup()
    Main_Frame.Show()
    app.MainLoop()
