#!/usr/bin/env python
'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def gen_fib(largest, last = 2, prev = 1, li = [1,2]):
	if last + prev > largest:
		return li
	li.append(last + prev)
	return gen_fib(largest, last+prev, last, li)

print sum([0 if x % 2 else x for x in gen_fib(4000000)])

