<?php
    $today = date("md");
    
    switch ($today) 
    {
    case 0212:
        echo "Happy Birthday Mr. Lincoln";
        break;
    case 0317:
        echo "Happy St. Patrick's Day";
        break;
    case 0401:
        echo "Be on the lookout for jokes!";
        break;
    case 0604:
        echo "Happy Independence Day!";
        break;
    case 1031:
        echo "Happy Halloween";
        break;
    case 1105:
        echo "Remember, remember the fifth of November.";
        break;
    case 1225:
        echo "Merry Christmas";
        break;
    case 1231:
        echo "Happy New Year";
        break;
    default:
        echo "Welcome to JoeGames.co.nr";
        break;
    }
?>
